config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "rss_subscriptions#index"
  resources :rss_subscriptions, path: "rss/subscriptions", only: [ :index, :new, :create, :destroy ]
  resources :rss_urls, path: "rss/urls", only: [ :index, :new, :create, :destroy ]
  post "events/line" => "events#line", as: :callback_line
end

app/models/rss_subscription.rb
class RssSubscription < ApplicationRecord
  belongs_to :user
  belongs_to :rss_url

  validates :user, presence: true
  validates :rss_url, presence: true
  validates :rss_url_id, uniqueness: {
    scope: :user_id,
    message: "is already subscribed by you"
  }

  validate :user_subscription_limit

  private

  def user_subscription_limit
    if user.present? && user.rss_subscriptions.count >= 100
      errors.add(:base, "You can't have more than 100 RSS subscriptions")
    end
  end
end

app/controllers/rss_subscriptions_controller.rb
class RssSubscriptionsController < ApplicationController
  before_action :set_current_user

  def index
    @rss_subscriptions = @current_user.rss_subscriptions
  end

  def new
    @rss_subscription = RssSubscription.new
    subscribed_rss_url_ids = @current_user.rss_subscriptions.pluck(:rss_url_id)
    @urls = RssUrl.where.not(id: subscribed_rss_url_ids)
  end

  def create
    @rss_subscription = RssSubscription.new(rss_subscription_params.merge(user: @current_user))
    if @rss_subscription.save
      redirect_to rss_subscriptions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @rss_subscription = RssSubscription.find(params[:id])
    @rss_subscription.destroy
    redirect_to rss_subscriptions_path
  end

  private

  def set_current_user
    @current_user ||= Current.session.user if Current.session
  end

  def rss_subscription_params
    params.expect([ rss_subscription: [ :rss_url_id ] ])
  end
end

app/helpers/rss_subscriptions_helper.rb
module RssSubscriptionsHelper
end

app/views/rss_subscriptions/index.html.erb
<h1>RSS Subscriptions</h1>
<div>
  <%= link_to "New Subscription", new_rss_subscription_path %>
</div>
<div id="rss-subscriptions">
  <ul>
    <% @rss_subscriptions.each do |rss_subscription| %>
      <li style="display: flex">
        <span><%= rss_subscription.rss_url.url %></span>
        <%= button_to "Delete",
        rss_subscription,
        method: :delete,
        data: {
          turbo_confirm: "Are you sure?",
        } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/rss_subscriptions/new.html.erb
<h1>Create new RSS Subscription</h1>
<div>
  <%= form_with model: @rss_subscription do |form| %>
    <div>
      <%= form.label :rss_url_id, "RSS URL" %>
      <%= form.select :rss_url_id, @urls.map { |url| [url.url, url.id] } %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  <%= link_to "Cancel", rss_subscriptions_path %>
</div>